Implement custom menu item layouts
yavski/fab-speed-dial pull request #19
Opened 2016-05-01 02:04 UTC by d-lord

Add menuItemLayoutStart and menuItemLayoutEnd to FabSpeedDial attributes

FAB will use them if defined, or default to the existing
fab_menu_item_[end|start] layouts.

Includes a sample custom layout and uses it in the Style sample
activity. (would it be better to add a new activity?)

Adds both new attributes to the README.

This change is intended to add functionality but be fully
backwards-compatible.

2016-06-21 20:32 UTC, ParthPadg commented
This is awesome! Although I love the default styling, it'd be nice to have the ability to custom-style the mini FABs.

2016-10-16 09:30 UTC, yavski requested changes
Sorry for taking ages to respond to your PR. Take a look at my feedback, I'll happily merge your work once you've updated the PR. Cheers.

2016-10-16 09:30 UTC, yavski commented on samples/src/main/res/layout/custom_fab_menu_item_end.xml
> +        android:id="@+id/card_view"
Define the id in the library module as an id resource, replace the ids of the default start/end layouts and reuse it here too.

2016-10-16 09:30 UTC, yavski commented on samples/src/main/res/layout/custom_fab_menu_item_end.xml
> +                android:id="@+id/title_view"
Same as above.

2016-10-16 09:30 UTC, yavski commented on samples/src/main/res/layout/custom_fab_menu_item_end.xml
> +                android:id="@+id/mini_fab"
Same as above.

2016-10-16 09:30 UTC, yavski commented on samples/src/main/res/layout/custom_fab_menu_item_start.xml
> +<?xml version="1.0" encoding="utf-8"?><!--
Make the same changes to this layout too.

2016-10-16 09:30 UTC, yavski commented on samples/src/main/res/layout/activity_style_sample.xml
> -            app:miniFabTitleTextColor="?attr/colorPrimaryDark" />
Leave this layout as it is and add a new activity to show how to use custom layouts for the menu items.

2017-08-29 16:17 UTC, DeadCounter commented
I'd love this feature to be implemented as well :) What's status on the changes requested @d-lord?

2017-08-30 01:57 UTC, d-lord commented
@DeadCounter I'm not working on Android any more, so it's unlikely to get done. Pull requests to the pull request would be welcome ;)

2022-05-26 04:25 UTC, d-lord commented
Hi folks, boy is this a blast from the past. Seems thoroughly stalled, and at this point my Android knowledge has decayed back to zero, so I'm just going to close it 😄

Anyone wanting to re-implement or extend it is welcome to use anything I've contributed.

2022-05-26 04:25 UTC, closed without merging